###############################################################################
##        Name: ns.ansible.yaml                                               #
##        Date: 29/12/2020                                                    #
##     Version: v0.1                                                          #
## Description: File to create a namespace for:                               #
##              + owner: ansible                                              #
##              + target: kubernetes_rfd                                      #
##----------------------------------------------------------------------------#
##      Editor: Jos√© Manuel Plana Santos                                      #
##     Contact: dev.josemanuelps@gmail.com                                    #
###############################################################################



---
apiVersion: v1
kind: Namespace
metadata:
  name: ns-ansible
  labels:
    owner: ansible
    target: kubernetes_rfd
    yaml_name: ns.ansible.yaml
    yaml_version: v0.1


